[model]
model = "ctm_with_innovations"
d_model = 512
dropout = 0.0
backbone_type = "resnet18-4"
pretrained_backbone = "none"
grayscale = false
convert_grayscale_to_rgb = false
d_input = 512
heads = 8
iterations = 50
positional_embedding_type = "none"

[model.innovations]
use_gsh = false
use_hne = false
use_sanp = false
hne_group_configs = null
hne_group_configs_file = null
sanp_init_top_k = 1000

[model.losses]
use_psl = false
lambda_psl = 0.1
use_ctcs = false
lambda_ctcs = 0.1

[model.ponder]
use_ponder_loss = false
lambda_p = 0.2
beta = 0.01
synapse_depth = 4
n_synch_out = 32
n_synch_action = 32
neuron_select_type = "first-last"
n_random_pairing_self = 0

[model.memory]
memory_length = 25
deep_memory = true
memory_hidden_dims = 4
dropout_nlm = 0.0
do_normalisation = false
