model: "ctm_gated"
d_model: 512
dropout: 0.0
backbone_type: "resnet18-4"
pretrained_backbone: "none"
grayscale: false
convert_grayscale_to_rgb: false
d_input: 128
heads: 4
iterations: 50
positional_embedding_type: "none"

gated:
  exit_strategy: "certainty"
  exit_threshold: 0.9
  min_steps: 1
  loss_type: "standard"

ponder:
  use_ponder_loss: false
  lambda_p: 0.2
  beta: 0.01
  synapse_depth: 4
  n_synch_out: 32
  n_synch_action: 32
  neuron_select_type: "first-last"
  n_random_pairing_self: 0

memory:
  memory_length: 25
  deep_memory: true
  memory_hidden_dims: 4
  dropout_nlm: 0.0
  do_normalisation: false