python -m tasks.image_classification.train \
  --model ctm_with_innovations \
  --d_model 512 \
  --d_input 256 \
  --synapse_depth 4 \
  --heads 8 \
  --n_synch_out 256 \
  --n_synch_action 256 \
  --n_random_pairing_self 0 \
  --neuron_select_type random \
  --iterations 50 \
  --memory_length 5 \
  --deep_memory \
  --memory_hidden_dims 16 \
  --dropout 0.2 \
  --no-do_normalisation \
  --positional_embedding_type none \
  --backbone_type resnet18-4 \
  --pretrained_backbone imagenet \
  --batch_size 64 \
  --batch_size_test 32 \
  --lr 5e-4 \
  --training_iterations 5001 \
  --warmup_steps 1000 \
  --use_scheduler \
  --scheduler_type cosine \
  --weight_decay 0.0 \
  --img_size 224 \
  --log_dir logs-lambda/rafdb/ctm_with_innovations/d=512--i=256--h=8--ns=256-random--iters=50x5--h=16--drop=0.2--pos=none--back=18x4--seed=42 \
  --dataset RAFDB \
  --data_root /kaggle/input/raf-db-dataset/DATASET \
  --save_every 250 \
  --track_every 125 \
  --seed 42 \
  --n_test_batches 50 \
  --use_amp \
  --device 0 \
  --use_gsh \
  --use_hne \
  --use_sanp \
  --hne_group_configs '[{"n_neurons": 170, "memory": 2, "hidden": 8}, {"n_neurons": 171, "memory": 3, "hidden": 16}, {"n_neurons": 171, "memory": 5, "hidden": 32}]' \
  --sanp_init_top_k 1000 \
  --hne_group_configs_file tasks/image_classification/scripts/hne_configs.json \
  --use_psl \
  --lambda_psl 0.1 \
  --use_ctcs \
  --lambda_ctcs 0.1
